#!/bin/bash

build ()
{
        source /etc/conf.d/ubrb.conf

	echo "upload your keyfile by running \"# ubrb ${device} S${store} \`cat ${file} | xxd -p -c \${sizeInByte}\`\""

	add_file "/etc/conf.d/ubrb.conf"
	add_binary "rm"
	add_binary "ubrb"
	add_binary "xxd"

	add_runscript
}

help ()
{
    cat<<HELPEOF
TODO
HELPEOF
}
